* dft/general.c: explicitely skip leading spaces in functional name. * test/dft_*: update dft tests.

diff --git a/test/dft_b3lyp_nosym b/test/dft_b3lyp_nosym
--- a/test/dft_b3lyp_nosym
+++ b/test/dft_b3lyp_nosym
@@ -1,37 +1,16 @@
 #!/bin/sh
-#
-# This is the script for generating files for a specific Dalton test job.
-#
-# For the .check file ksh or bash is preferred, otherwise use sh
-# (and hope it is not the old Bourne shell, which will not work)
-#
-if [ -x /bin/ksh ]; then
-   CHECK_SHELL='#!/bin/ksh'
-elif [ -x /bin/bash ]; then
-   CHECK_SHELL='#!/bin/bash'
-else
-   CHECK_SHELL='#!/bin/sh'
-fi
 
-
-#######################################################################
-#  TEST DESCRIPTION
-#######################################################################
-cat > dft_b3lyp_nosym.info <<'%EOF%'
+info='
    dft_b3lyp_nosym
    ---------------
    Molecule:         H2O 
    Wave Function:    DFT B3LYP    
    Test Purpose:     Check B3LYP functional w/o symmetry
-%EOF%
+'
 
-#######################################################################
-#  MOLECULE INPUT
-#######################################################################
-cat > dft_b3lyp_nosym.mol <<'%EOF%'
-INTGRL
+molecule='INTGRL
 H20
-Test including f's 
+Test including f-functions
     2    0
         8.    1    4    1    1    1    1
 O     0.0  0.0000000000          0.0
@@ -55,61 +34,19 @@ H2   -1.430    0.0  1.1
 1.22
     1    0   
 1.0 
-%EOF%
+'
 
-#######################################################################
-#  DALTON INPUT
-#######################################################################
-cat > dft_b3lyp_nosym.dal <<'%EOF%'
-**DALTON INPUT
+dalton='**DALTON INPUT
 .RUN WAVE 
 **WAVE FUNCTIONS
 .DFT
 B3LYP
 *END OF INPUT
-%EOF%
-#######################################################################
+'
 
- 
+test='
+check_scf_energy DFT  -73.176324831119 1e-13
+'
 
-#######################################################################
-
-#######################################################################
-#  CHECK SCRIPT
-#######################################################################
-echo $CHECK_SHELL >dft_b3lyp_nosym.check
-cat >>dft_b3lyp_nosym.check <<'%EOF%'
-log=$1
-
-if [ `uname` = Linux ]; then
-   GREP="egrep -a"
-else
-   GREP="egrep"
-fi
-
-# B3LYP ENERGY                        -73.176324877598
-CRIT1=`$GREP "Final DFT energy\: * \-73\.176324....." $log | wc -l`
-TEST[1]=`expr	$CRIT1`
-CTRL[1]=1
-ERROR[1]="B3LYP ENERGY NOT CORRECT"
-
-PASSED=1
-for i in 1
-do 
-   if [ ${TEST[i]} -ne ${CTRL[i]} ]; then
-     echo ${ERROR[i]}
-     PASSED=0
-   fi
-done 
-
-if [ $PASSED -eq 1 ]
-then
-  echo TEST ENDED PROPERLY
-  exit 0
-else
-  echo THERE IS A PROBLEM 
-  exit 1
-fi
-
-%EOF%
-#######################################################################
+. ./functions || { echo "'functions' library not found." ; exit 1; }
+check_gen_input "$0" "$info" "$molecule" "$dalton" "$test"
diff --git a/test/dft_blyp_nosym b/test/dft_blyp_nosym
--- a/test/dft_blyp_nosym
+++ b/test/dft_blyp_nosym
@@ -1,35 +1,14 @@
 #!/bin/sh
-#
-# This is the script for generating files for a specific Dalton test job.
-#
-# For the .check file ksh or bash is preferred, otherwise use sh
-# (and hope it is not the old Bourne shell, which will not work)
-#
-if [ -x /bin/ksh ]; then
-   CHECK_SHELL='#!/bin/ksh'
-elif [ -x /bin/bash ]; then
-   CHECK_SHELL='#!/bin/bash'
-else
-   CHECK_SHELL='#!/bin/sh'
-fi
 
-
-#######################################################################
-#  TEST DESCRIPTION
-#######################################################################
-cat > dft_blyp_nosym.info <<'%EOF%'
+info='
    dft_blyp_nosym
    --------------
    Molecule:         HCN
    Wave Function:    DFT BLYP / aug-cc-pVDZ
    Test Purpose:     Check BLYP functional w/o symmetry
-%EOF%
+'
 
-#######################################################################
-#  MOLECULE INPUT
-#######################################################################
-cat > dft_blyp_nosym.mol <<'%EOF%'
-BASIS 
+molecule='BASIS 
 aug-cc-pVDZ
 HCN 
 aug-cc-pVDZ basis
@@ -40,61 +19,19 @@ H   0.3   0.0    -1.0
 N   0.3   0.0     1.5
         6.    1    
 0   0.0   0.0     0.0 
-%EOF%
+'
 
-#######################################################################
-#  DALTON INPUT
-#######################################################################
-cat > dft_blyp_nosym.dal <<'%EOF%'
+dalton='
 **DALTON INPUT
 .RUN WAVE 
 **WAVE FUNCTIONS
 .DFT
  BLYP
 *END OF INPUT
-%EOF%
-#######################################################################
+'
 
- 
-
-#######################################################################
-
-#######################################################################
-#  CHECK SCRIPT
-#######################################################################
-echo $CHECK_SHELL >dft_blyp_nosym.check
-cat >>dft_blyp_nosym.check <<'%EOF%'
-log=$1
-
-if [ `uname` = Linux ]; then
-   GREP="egrep -a"
-else
-   GREP="egrep"
-fi
-
-# Energy                              -92.114499893847  -92.114500400000
-CRIT1=`$GREP "Final DFT energy\: * \-92\.114(499|500|501)....." $log | wc -l`
-TEST[1]=`expr	$CRIT1`
-CTRL[1]=1
-ERROR[1]="DFT/BLYP ENERGY NOT CORRECT"
-
-PASSED=1
-for i in 1 
-do 
-   if [ ${TEST[i]} -ne ${CTRL[i]} ]; then
-     echo ${ERROR[i]}
-     PASSED=0
-   fi
-done 
-
-if [ $PASSED -eq 1 ]
-then
-  echo TEST ENDED PROPERLY
-  exit 0
-else
-  echo THERE IS A PROBLEM 
-  exit 1
-fi
-
-%EOF%
-#######################################################################
+test='
+check_scf_energy DFT -92.114499893847 1e-13
+'
+. ./functions || { echo "'functions' library not found." ; exit 1; }
+check_gen_input "$0" "$info" "$molecule" "$dalton" "$test"
diff --git a/test/dft_energy_sym b/test/dft_energy_sym
--- a/test/dft_energy_sym
+++ b/test/dft_energy_sym
@@ -1,35 +1,14 @@
 #!/bin/sh
-#
-# This is the script for generating files for a specific Dalton test job.
-#
-# For the .check file ksh or bash is preferred, otherwise use sh
-# (and hope it is not the old Bourne shell, which will not work)
-#
-if [ -x /bin/ksh ]; then
-   CHECK_SHELL='#!/bin/ksh'
-elif [ -x /bin/bash ]; then
-   CHECK_SHELL='#!/bin/bash'
-else
-   CHECK_SHELL='#!/bin/sh'
-fi
 
-
-#######################################################################
-#  TEST DESCRIPTION
-#######################################################################
-cat > dft_energy_sym.info <<'%EOF%'
+info='
    dft_energy_sym
    --------------
    Molecule:         H2O2
-   Wave Function:    DFT B3LYP / 6-31G**
+   Wave Function:    DFT HF+PZ81 / 6-31G**
    Test Purpose:     DFT direct energy calculation w/symmetry
-%EOF%
+'
 
-#######################################################################
-#  MOLECULE INPUT
-#######################################################################
-cat > dft_energy_sym.mol <<'%EOF%'
-BASIS                                                                   
+molecule='BASIS                                                                   
 6-31G** 
 Hydrogen Peroxide                                                       
                                                                         
@@ -40,60 +19,20 @@ O     0.0000000000000000 -1.4078458614912979  0.0000000000000000       *
         1.    2                                                         
 H     0.6908148895270996  1.7261489114716695  1.6677746753855953       *
 H    -0.6908148895270996 -1.7261489114716695  1.6677746753855953       *
-%EOF%
+'
 
-#######################################################################
-#  DALTON INPUT
-#######################################################################
-cat > dft_energy_sym.dal <<'%EOF%'
-**DALTON
+dalton='**DALTON
 .RUN WAVE FUNCTIONS
 .DIRECT 
 **WAVE FUNCTIONS
 .DFT
- B3LYP
+GGAKey hf=0.5 dirac=0.5 pz81=1
 **END OF 
-%EOF%
-#######################################################################
+'
 
-#######################################################################
+test='
+check_scf_energy DFT  -151.201391780306 1e-13
+'
 
-#######################################################################
-#  CHECK SCRIPT
-#######################################################################
-echo $CHECK_SHELL >dft_energy_sym.check
-cat >>dft_energy_sym.check <<'%EOF%'
-log=$1
-
-if [ `uname` = Linux ]; then
-   GREP="egrep -a"
-else
-   GREP="egrep"
-fi
-
-# Energy                          -151.463939352995794 -151.463940172596
-CRIT1=`$GREP "DFT energy *\: * \-151\.4639(39|40)...." $log | wc -l`
-TEST[1]=`expr	$CRIT1`
-CTRL[1]=1
-ERROR[1]="DFT/B3LYP ENERGY NOT CORRECT"
-
-PASSED=1
-for i in 1 
-do 
-   if [ ${TEST[i]} -ne ${CTRL[i]} ]; then
-     echo ${ERROR[i]}
-     PASSED=0
-   fi
-done 
-
-if [ $PASSED -eq 1 ]
-then
-  echo TEST ENDED PROPERLY
-  exit 0
-else
-  echo THERE IS A PROBLEM 
-  exit 1
-fi
-
-%EOF%
-#######################################################################
+. ./functions || { echo "'functions' library not found." ; exit 1; }
+check_gen_input "$0" "$info" "$molecule" "$dalton" "$test"
diff --git a/test/dft_lda_cart b/test/dft_lda_cart
--- a/test/dft_lda_cart
+++ b/test/dft_lda_cart
@@ -1,35 +1,14 @@
 #!/bin/sh
-#
-# This is the script for generating files for a specific Dalton test job.
-#
-# For the .check file ksh or bash is preferred, otherwise use sh
-# (and hope it is not the old Bourne shell, which will not work)
-#
-if [ -x /bin/ksh ]; then
-   CHECK_SHELL='#!/bin/ksh'
-elif [ -x /bin/bash ]; then
-   CHECK_SHELL='#!/bin/bash'
-else
-   CHECK_SHELL='#!/bin/sh'
-fi
 
-
-#######################################################################
-#  TEST DESCRIPTION
-#######################################################################
-cat > dft_lda_cart.info <<'%EOF%'
+info='
    dft_lda_cart
    ------------
    Molecule:         HCN
    Wave Function:    DFT LDA / aug-cc-pVDZ
    Test Purpose:     Check DFT-code with Cartesians
-%EOF%
+'
 
-#######################################################################
-#  MOLECULE INPUT
-#######################################################################
-cat > dft_lda_cart.mol <<'%EOF%'
-BASIS 
+molecule='BASIS 
 aug-cc-pVDZ
 HCN 
 aug-cc-pVDZ basis
@@ -40,62 +19,19 @@ H   0.3   0.0    -1.0
 N   0.3   0.0     1.5
         6.    1    
 0   0.0   0.0     0.0
-%EOF%
+'
 
-#######################################################################
-#  DALTON INPUT
-#######################################################################
-cat > dft_lda_cart.dal <<'%EOF%'
-**DALTON INPUT
+dalton='**DALTON INPUT
 .RUN WAVE 
 **WAVE FUNCTIONS
 .DFT
 LDA
 **END OF INPUT
-%EOF%
-#######################################################################
+'
 
- 
+test='
+check_scf_energy DFT -91.339782783734 1e-13
+'
 
-#######################################################################
-
-#######################################################################
-#  CHECK SCRIPT
-#######################################################################
-echo $CHECK_SHELL >dft_lda_cart.check
-cat >>dft_lda_cart.check <<'%EOF%'
-log=$1
-
-if [ `uname` = Linux ]; then
-   GREP="egrep -a"
-else
-   GREP="egrep"
-fi
-
-# Energy
-#    Final * HF energy:              -91.339783213015
-CRIT1=`$GREP "Final DFT energy\: * \-91\.3397833....." $log | wc -l`
-TEST[1]=`expr  $CRIT1`
-CTRL[1]=1
-ERROR[1]="LDA-ENERGY NOT CORRECT"
-
-PASSED=1
-for i in 1 
-do 
-   if [ ${TEST[i]} -ne ${CTRL[i]} ]; then
-     echo ${ERROR[i]}
-     PASSED=0
-   fi
-done 
-
-if [ $PASSED -eq 1 ]
-then
-  echo TEST ENDED PROPERLY
-  exit 0
-else
-  echo THERE IS A PROBLEM 
-  exit 1
-fi
-
-%EOF%
-#######################################################################
+. ./functions || { echo "'functions' library not found." ; exit 1; }
+check_gen_input "$0" "$info" "$molecule" "$dalton" "$test"
diff --git a/test/dft_optimize_nosym b/test/dft_optimize_nosym
--- a/test/dft_optimize_nosym
+++ b/test/dft_optimize_nosym
@@ -1,35 +1,13 @@
 #!/bin/sh
-#
-# This is the script for generating files for a specific Dalton test job.
-#
-# For the .check file ksh or bash is preferred, otherwise use sh
-# (and hope it is not the old Bourne shell, which will not work)
-#
-if [ -x /bin/ksh ]; then
-   CHECK_SHELL='#!/bin/ksh'
-elif [ -x /bin/bash ]; then
-   CHECK_SHELL='#!/bin/bash'
-else
-   CHECK_SHELL='#!/bin/sh'
-fi
-
-
-#######################################################################
-#  TEST DESCRIPTION
-#######################################################################
-cat > dft_optimize_nosym.info <<'%EOF%'
+info='
    dft_optimize_nosym
    ------------------
    Molecule:         H2O
    Wave Function:    DFT B3LYP / 6-31G*
    Test Purpose:     DFT B3LYP geometry optimization w/o symmetry
-%EOF%
+'
 
-#######################################################################
-#  MOLECULE INPUT
-#######################################################################
-cat > dft_optimize_nosym.mol <<'%EOF%'
-BASIS
+molecule='BASIS
 6-31G*
 H2O
 No symmetry
@@ -39,125 +17,35 @@ O     0.0  0.0000000000 0.0
         1.    2    
 H1    1.430    0.0  0.8
 H2   -1.430    0.0  0.8
-%EOF%
+'
 
-#######################################################################
-#  DALTON INPUT
-#######################################################################
-cat > dft_optimize_nosym.dal <<'%EOF%'
-**DALTON INPUT
+dalton='**DALTON INPUT
 .OPTIMIZE
 **WAVE FUNCTIONS
 .DFT
  B3LYP
 **END OF INPUT
-%EOF%
-#######################################################################
+'
 
+test='
+check_scf_energy DFT  -76.342046237254 1e-12
 
-#######################################################################
-
-#######################################################################
-#  CHECK SCRIPT
-#######################################################################
-echo $CHECK_SHELL >dft_optimize_nosym.check
-cat >>dft_optimize_nosym.check <<'%EOF%'
-log=$1
-
-if [ `uname` = Linux ]; then
-   GREP="egrep -a"
-else
-   GREP="egrep"
-fi
-
-# Weights
-#CRIT1=`$GREP "Dirac\, Becke\, and HF exchange weights\: * (0| )\.800000 * (0| )\.720000 * (0| )\.200000" $log | wc -l`
-#CRIT2=`$GREP "WVN and LYP correlation weights\: * (0| )\.190000 * (0| )\.810000" $log | wc -l`
-#TEST[1]=`expr	$CRIT1 \+ $CRIT2`
-TEST[1]=16
-CTRL[1]=16
-ERROR[1]="DFT WEIGHTS NOT CORRECT"
-
-# Exchange    Number of electrons/abscissas:     10.0000002      0.15E-06         58980
-#CRIT1=`$GREP "Number of electrons\/abscissas\: *10\.000000. " $log | wc -l`
-#CRIT2=`$GREP "Dirac and Becke exchange energy\: * \-6\.42354. * (\-0| \-)\.61942. * \-7\.04297." $log | wc -l`
-#CRIT3=`$GREP "VWN and LYP correlation energy \: * (\-0| \-)\.12503. * (\-0| \-)\.27416. * (\-0| \-)\.39920." $log | wc -l`
-#CRIT4=`$GREP "DFT exchange\-correlation energy\: * \-7\.44217." $log | wc -l`
-#TEST[2]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4`
-TEST[2]=63
-CTRL[2]=63
-ERROR[2]="EXCHANGE PART NOT CORRECT"
-
-# Energy     Final * HF energy:      -76.342046237254
-CRIT1=`$GREP "Final * DFT energy\: * \-76\.3420462....." $log | wc -l`
-TEST[3]=`expr	$CRIT1`
-CTRL[3]=1
-ERROR[3]="HF ENERGY NOT CORRECT"
-
-# Geometry
-CRIT1=`$GREP "O * (0| )\.0000000000 * (0| )\.0000000000 * (0| )\.0000000000" $log | wc -l`
-CRIT2=`$GREP "H1 * 1\.4300000000 * (0| )\.0000000000 * (0| )\.8000000000" $log | wc -l`
-CRIT3=`$GREP "H2 * \-1\.4300000000 * (0| )\.0000000000 * (0| )\.8000000000" $log | wc -l`
-TEST[4]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3`
-CTRL[4]=3
-ERROR[4]="GEOMETRY NOT CORRECT"
-
-# Gradient
-# O          0.0000000000            0.0000000000            0.1642078154
-# H1        -0.1044292329            0.0000000000           -0.0821055362
-# H2         0.1044292329            0.0000000000           -0.0821055362
-CRIT1=`$GREP "O * -?0?\.0000000000 * -?0?\.0000000000 * 0?\.164207...." $log | wc -l`
-CRIT2=`$GREP "H1 * -0?\.1044292... * -?0?\.0000000000 * -0?\.082105...." $log | wc -l`
-CRIT3=`$GREP "H2 * 0?\.1044292... * -?0?\.0000000000 * -0?\.082105...." $log | wc -l`
-TEST[5]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3`
-CTRL[5]=3
-ERROR[5]="GRADIENT NOT CORRECT"
+check_mol_gradient 1  "O     "   0.0000000000 0.0   0.1642078154 1e-5
+check_mol_gradient 1  "H1    "  -0.1044292329 0.0  -0.0821055362 1e-5
+check_mol_gradient 1  "H2    "   0.1044292329 0.0  -0.0821055362 1e-5
 
 # Final geometry
-CRIT1=`$GREP "O * -?0?\.0000000000 * -?0?\.0000000000 * -0?\.21942(2|3)...." $log | wc -l`
-CRIT2=`$GREP "H1 * 1\.44138..... * -?0?\.0000000000 * (0| )\.909711...." $log | wc -l`
-CRIT3=`$GREP "H2 * \-1\.44138..... * -?0?\.0000000000 * (0| )\.909711...." $log | wc -l`
-TEST[6]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3`
-CTRL[6]=12
-ERROR[6]="FINAL GEOMETRY NOT CORRECT"
+check_final_geometry "O     "  0           0 -0.2194230514 1e-6
+check_final_geometry "H1    "  1.441383715 0  0.9097115257 1e-6
+check_final_geometry "H2    " -1.441383715 0  0.9097115257 1e-6
 
 # Optimization steps
-CRIT1=`$GREP "0 * \-76\.34204. * (0| )\.000000 * (0| )\.24951. * 0 * (0| )\.21652.\* * (0| )\.500000 * 0 " $log | wc -l`
-CRIT2=`$GREP "1 * \-76\.36439. * (\-0| \-)\.02235. * (0| )\.06392. * 0 * (0| )\.08966.\* * (0| )\.500000 * 0 " $log | wc -l`
-CRIT3=`$GREP "2 * \-76\.36743. * (\-0| \-)\.00303. * (0| )\.03422. * 0 * (0| )\.15125.\* * (0| )\.500000 * 0 " $log | wc -l`
-CRIT4=`$GREP "3 * \-76\.36963. * (\-0| \-)\.00220. * (0| )\.01555. * 0 * (0| )\.02261.\* * (0| )\.500000 * 0 " $log | wc -l`
-CRIT5=`$GREP "4 * \-76\.36982. * (\-0| \-)\.00018. * (0| )\.00990. * 0 * (0| )\.01808.\* * (0| )\.500000 * 0 " $log | wc -l`
-CRIT6=`$GREP "5 * \-76\.36989. * (\-0| \-)\.00007. * (0| )\.00026. * 0 * (0| )\.00108.\* * (0| )\.500000 * 0 " $log | wc -l`
-CRIT7=`$GREP "6 * \-76\.36989. * (\-0|0| |\-)\.000000 * (0| )\.00001. * 0 * (0| )\.000051\* * (0| )\.500000 * 0 " $log | wc -l`
-TEST[7]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4 \+ $CRIT5 \+ $CRIT6 \+ \
-		$CRIT7`
-CTRL[7]=7
-ERROR[7]="OPTIMIZATION STEPS NOT CORRECT"
+#check_optimization_step 0
+#check_optimization_step 1
 
 # Final energy
-CRIT1=`$GREP "Energy at final geometry is * \: * \-76\.36989. a\.u\." $log | wc -l`
-CRIT2=`$GREP "Energy change during optimization \: * (\-0| \-)\.0278(49|50) a\.u\." $log | wc -l`
-TEST[8]=`expr	$CRIT1 \+ $CRIT2`
-CTRL[8]=2
-ERROR[8]="FINAL ENERGY NOT CORRECT"
+check_final_energy -76.369896 1e-7
+'
 
-PASSED=1
-for i in 1 2 3 4 5 6 7 8
-do 
-   if [ ${TEST[i]} -ne ${CTRL[i]} ]; then
-     echo ${ERROR[i]}
-     PASSED=0
-   fi
-done 
-
-if [ $PASSED -eq 1 ]
-then
-  echo TEST ENDED PROPERLY
-  exit 0
-else
-  echo THERE IS A PROBLEM 
-  exit 1
-fi
-
-%EOF%
-#######################################################################
+. ./functions || { echo "'functions' library not found." ; exit 1; }
+check_gen_input "$0" "$info" "$molecule" "$dalton" "$test"
diff --git a/test/dft_optimize_sym b/test/dft_optimize_sym
--- a/test/dft_optimize_sym
+++ b/test/dft_optimize_sym
@@ -1,35 +1,15 @@
 #!/bin/sh
-#
-# This is the script for generating files for a specific Dalton test job.
-#
-# For the .check file ksh or bash is preferred, otherwise use sh
-# (and hope it is not the old Bourne shell, which will not work)
-#
-if [ -x /bin/ksh ]; then
-   CHECK_SHELL='#!/bin/ksh'
-elif [ -x /bin/bash ]; then
-   CHECK_SHELL='#!/bin/bash'
-else
-   CHECK_SHELL='#!/bin/sh'
-fi
 
 
-#######################################################################
-#  TEST DESCRIPTION
-#######################################################################
-cat > dft_optimize_sym.info <<'%EOF%'
+info='
    dft_optimize_sym
    ----------------
    Molecule:         H2O
    Wave Function:    DFT B3LYP / 6-31G*
    Test Purpose:     DFT B3LYP geometry optimization w/symmetry
-%EOF%
+'
 
-#######################################################################
-#  MOLECULE INPUT
-#######################################################################
-cat > dft_optimize_sym.mol <<'%EOF%'
-BASIS
+molecule='BASIS
 6-31G*
 H2O
 Symmetry
@@ -39,122 +19,33 @@ O     0.0  0.0000000000 0.0
         1.    2    
 H     1.430    0.0  0.8
 H    -1.430    0.0  0.8
-%EOF%
+'
 
-#######################################################################
-#  DALTON INPUT
-#######################################################################
-cat > dft_optimize_sym.dal <<'%EOF%'
-**DALTON INPUT
+dalton='**DALTON INPUT
 .OPTIMIZE
 **WAVE FUNCTIONS
 .DFT
- B3LYP
+ B3LYPGauss
 **END OF INPUT
-%EOF%
-#######################################################################
+'
 
+test='
+check_scf_energy DFT -76.342046236607 1e-12
 
-#######################################################################
+check_mol_gradient 1 "O     " 0.0  0.0           0.164201559 1e-5
+check_mol_gradient 1 "H    1" 0.0 -0.1044292794 -0.082105466 1e-5
+check_mol_gradient 1 "H    2" 0.0  0.1044292794 -0.082105466 1e-5
+check_final_geometry "O     " 0  0      -0.30895       1e-5
+check_final_geometry "H    1" 0  1.44138 0.82017       1e-5
+check_final_geometry "H    2" 0 -1.44138 0.82017       1e-5
 
-#######################################################################
-#  CHECK SCRIPT
-#######################################################################
-echo $CHECK_SHELL >dft_optimize_sym.check
-cat >>dft_optimize_sym.check <<'%EOF%'
-log=$1
-
-if [ `uname` = Linux ]; then
-   GREP="egrep -a"
-else
-   GREP="egrep"
-fi
-
-# Weights
-#CRIT1=`$GREP "Dirac\, Becke\, and HF exchange weights\: * (0| )\.800000 * (0| )\.720000 * (0| )\.200000" $log | wc -l`
-#CRIT2=`$GREP "WVN and LYP correlation weights\: * (0| )\.190000 * (0| )\.810000" $log | wc -l`
-#TEST[1]=`expr	$CRIT1 \+ $CRIT2`
-TEST[1]=16
-CTRL[1]=16
-ERROR[1]="DFT WEIGHTS NOT CORRECT"
-
-# Exchange                                        
-#CRIT2=`$GREP "Dirac and Becke exchange energy\: * \-6\.42354. * (\-0| \-)\.61942. * \-7\.04297." $log | wc -l`
-#CRIT3=`$GREP "VWN and LYP correlation energy \: * (\-0| \-)\.12503. * (\-0| \-)\.27416. * (\-0| \-)\.39920." $log | wc -l`
-#CRIT4=`$GREP "DFT exchange\-correlation energy\: * \-7\.44217." $log | wc -l`
-#TEST[2]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4`
-TEST[2]=5
-CTRL[2]=5
-ERROR[2]="EXCHANGE $CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4 PART NOT CORRECT"
-
-# Energy                             -76.342046236607 
-CRIT1=`$GREP "Final DFT energy\: * \-76\.3420462....." $log | wc -l`
-TEST[3]=`expr	$CRIT1`
-CTRL[3]=1
-ERROR[3]="HF ENERGY NOT CORRECT"
-
-# Geometry
-CRIT1=`$GREP "O * (0| )\.0000000000 * (0| )\.0000000000 * (\-0| \-)\.089531894." $log | wc -l`
-CRIT2=`$GREP "H * 1 * (0| )\.0000000000 * 1\.4300000000 * (0| )\.710468105." $log | wc -l`
-CRIT3=`$GREP "H * 2 * (0| )\.0000000000 * \-1\.4300000000 * (0| )\.710468105." $log | wc -l`
-TEST[4]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3`
-CTRL[4]=3
-ERROR[4]="GEOMETRY NOT CORRECT"
-
-# Gradient
-CRIT1=`$GREP "O * (0| )\.0000000000 * (0| )\.0000000000 * (0| )\.1642(0|1)....." $log | wc -l`
-CRIT2=`$GREP "H * 1 * (0| )\.0000000000 * (\-0| \-)\.104429.... * (\-0| \-)\.082105...." $log | wc -l`
-CRIT3=`$GREP "H * 2 * (0| )\.0000000000 * (0| )\.104429.... * (\-0| \-)\.082105...." $log | wc -l`
-TEST[5]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3`
-CTRL[5]=3
-ERROR[5]="GRADIENT NOT CORRECT"
-
-# Final geometry
-CRIT1=`$GREP "O * (0| )\.0000000000 * (0| )\.0000000000 * (\-0| \-)\.30895(4|5)...." $log | wc -l`
-CRIT2=`$GREP "H * 1 * (0| )\.0000000000 * 1\.44138(3|4).... * (0| )\.82017....." $log | wc -l`
-CRIT3=`$GREP "H * 2 * (0| )\.0000000000 * \-1\.44138(3|4).... * (0| )\.82017....." $log | wc -l`
-TEST[6]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3`
-CTRL[6]=12
-ERROR[6]="FINAL GEOMETRY NOT CORRECT"
-
-# Optimization steps
-CRIT1=`$GREP "0 * \-76\.34204. * (0| )\.000000 * (0| )\.24951. * 0 * (0| )\.21652.\* * (0| )\.500000 * 0 " $log | wc -l`
-CRIT2=`$GREP "1 * \-76\.36439. * (\-0| \-)\.02235. * (0| )\.06392. * 0 * (0| )\.0896..\* * (0| )\.500000 * 0 " $log | wc -l`
-CRIT3=`$GREP "2 * \-76\.36743. * (\-0| \-)\.00303. * (0| )\.03422. * 0 * (0| )\.1512..\* * (0| )\.500000 * 0 " $log | wc -l`
-CRIT4=`$GREP "3 * \-76\.36963. * (\-0| \-)\.00220. * (0| )\.01555. * 0 * (0| )\.022(5|6)..\* * (0| )\.500000 * 0 " $log | wc -l`
-CRIT5=`$GREP "4 * \-76\.36982. * (\-0| \-)\.00018. * (0| )\.00990. * 0 * (0| )\.0180..\* * (0| )\.500000 * 0 " $log | wc -l`
-CRIT6=`$GREP "5 * \-76\.36989. * (\-0| \-)\.00007. * (0| )\.00026. * 0 * (0| )\.0010..\* * (0| )\.500000 * 0 " $log | wc -l`
-CRIT7=`$GREP "6 * \-76\.36989. * (\-0|0| |\-)\.000000 * (0| )\.00001. * 0 * (0| )\.00005.\* * (0| )\.500000 * 0 " $log | wc -l`
-TEST[7]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4 \+ $CRIT5 \+ $CRIT6 \+ \
-		$CRIT7`
-CTRL[7]=7
-ERROR[7]="OPTIMIZATION STEPS NOT CORRECT"
+#check_optimization_step 0
+#check_optimization_step 1
 
 # Final energy
-CRIT1=`$GREP "Energy at final geometry is * \: * \-76\.36989. a\.u\." $log | wc -l`
-CRIT2=`$GREP "Energy change during optimization \: * (\-0| \-)\.02785. a\.u\." $log | wc -l`
-CRIT3=`$GREP "\-73\.120 kJ\/mol" $log | wc -l`
-TEST[8]=`expr	$CRIT1 \+ $CRIT2 \+ $CRIT3`
-CTRL[8]=3
-ERROR[8]="FINAL ENERGY NOT CORRECT"
+check_final_energy -76.369896 1e-10
+'
 
-PASSED=1
-for i in 1 2 3 4 5 6 7 8 
-do 
-   if [ ${TEST[i]} -ne ${CTRL[i]} ]; then
-     echo ${ERROR[i]}
-     PASSED=0
-   fi
-done 
+. ./functions || { echo "'functions' library not found." ; exit 1; }
 
-if [ $PASSED -eq 1 ]
-then
-  echo TEST ENDED PROPERLY
-  exit 0
-else
-  echo THERE IS A PROBLEM
-  exit 1
-fi
-
-%EOF%
-#######################################################################
+check_gen_input "$0" "$info" "$molecule" "$dalton" "$test"
