* dft/grid-gen.c: extra safety tests needed. * test/dft_b3lyp_magsus_nosym: convert it to the new format * test/functions: additional functions./pawsa

diff --git a/test/functions b/test/functions
--- a/test/functions
+++ b/test/functions
@@ -55,6 +55,32 @@ fi
 # ###################################################################
 # miscellaneous tests listed here.
 
+# check_basis:
+# check whether number of primitives and contraction parameters
+# are as expected. Unlikely to fail but...
+# $1 - name of the basis set
+# $2 - string like "H 1 1 4s1p 2s1p" containing
+#      atom label, number of atoms with this label, charge, 
+#      number of primitives, number of contracted functions,
+#      types of primitives and contracted functions.
+check_basis() {
+if [ "$2" = "" ]; then echo "not enough parameters to $0"; return 1; fi
+$AWK -v"s=$2" '
+/Basis set used is /{
+split(s,a)
+getline;getline;getline
+for(i=1; a[i] != ""; i+=4) {
+getline;
+if(a[i] != $1 || a[i+1] != $2 || a[i+2] != $3 || a[i+3] != $6) {
+    print; print a[i], a[i+1], a[i+2], a[i+3]
+    exit(1)
+}
+}
+done=1
+}
+END {exit(done ? 0 : 1)}' $log || ERRLIST="$ERRLIST; BASIS-SET"
+}
+
 # check_scf_energy:
 # $1 - calculation type: HF|DFT
 # $2 - expected energy
@@ -377,4 +403,98 @@ $AWK 'function e(v,r){#print "checking ",v, r;
 return(v>r||v<-r)}
 $1== "##" && $2 == '$1' && $7=='$3' { exit(e($8-('$3'),'$4'))  }
 ' $log || ERRLIST="$ERRLIST; ORB. GRADIENT $1"
+}
+
+check_magnetizabilities() {
+return 0
+}
+
+# check_mag_tensors:
+# check magnetizability tensors, total, diamagnetic and paramagnetic
+# contributions.
+# $1 - threshold
+# $2 - total tensor
+# $3 - nuclear contribution to the tensor
+# $4 - electronic contribution to the tensor
+check_mag_tensors() {
+if [ "$4" = "" ]; then
+    echo "not enough parameters to check_mag_tensors."; return 1
+fi
+
+awk -v "tol=$1" -v "t=`echo $2`" -v "d=`echo $3`" -v "p=`echo $4`" '
+function e(v,r){return(v>r||v<-r)}
+/Total magnetizability tensor/ {
+split(t,a); for(i=0;i<5;i++)getline;
+if(e($2-a[1],tol) || e($3-a[2],tol) ||e($4-a[3],tol)) exit 1
+getline;
+if(e($2-a[4],tol) || e($3-a[5],tol) ||e($4-a[6],tol)) exit 1
+getline;
+if(e($2-a[7],tol) || e($3-a[8],tol) ||e($4-a[9],tol)) exit 1
+foundt=1
+}
+/Diamagnetic magnetizability tensor/ {
+split(d,a); for(i=0;i<5;i++)getline;
+if(e($2-a[1],tol) || e($3-a[2],tol) ||e($4-a[3],tol)) exit 1
+getline;
+if(e($2-a[4],tol) || e($3-a[5],tol) ||e($4-a[6],tol)) exit 1
+getline;
+if(e($2-a[7],tol) || e($3-a[8],tol) ||e($4-a[9],tol)) exit 1
+foundd=1
+}
+/Paramagnetic magnetizability tensor/ {
+split(p,a); for(i=0;i<5;i++)getline;
+if(e($2-a[1],tol) || e($3-a[2],tol) ||e($4-a[3],tol)) exit 1
+getline;
+if(e($2-a[4],tol) || e($3-a[5],tol) ||e($4-a[6],tol)) exit 1
+getline;
+if(e($2-a[7],tol) || e($3-a[8],tol) ||e($4-a[9],tol)) exit 1
+foundp=1
+}
+END{exit( (foundt && foundd && foundp) ? 0 : 1) }
+' $log  || ERRLIST="$ERRLIST; MAGNETIZABILITY TENSORS"
+}
+
+# check_g_tensors:
+# check g-tensors, total, nuclear and electronic
+# contributions.
+# $1 - threshold
+# $2 - total tensor
+# $3 - nuclear contribution to the tensor
+# $4 - electronic contribution to the tensor
+check_g_tensors() {
+if [ "$4" = "" ]; then
+    echo "not enough parameters to check_mag_tensors."; return 1
+fi
+
+awk -v "tol=$1" -v "t=`echo $2`" -v "nu=`echo $3`" -v "el=`echo $4`" '
+function e(v,r){return(v>r||v<-r)}
+/Molecular g-tensor in principal axis system/ {
+split(t,a); for(i=0;i<3;i++)getline;
+if(e($2-a[1],tol) || e($3-a[2],tol) ||e($4-a[3],tol)) exit 1
+getline;
+if(e($2-a[4],tol) || e($3-a[5],tol) ||e($4-a[6],tol)) exit 1
+getline;
+if(e($2-a[7],tol) || e($3-a[8],tol) ||e($4-a[9],tol)) exit 1
+foundt=1
+}
+/Nuclear contribution in principal axis system/ {
+split(nu,a); for(i=0;i<3;i++)getline;
+if(e($2-a[1],tol) || e($3-a[2],tol) ||e($4-a[3],tol)) exit 1
+getline;
+if(e($2-a[4],tol) || e($3-a[5],tol) ||e($4-a[6],tol)) exit 1
+getline;
+if(e($2-a[7],tol) || e($3-a[8],tol) ||e($4-a[9],tol)) exit 1
+foundn=1
+}
+/Electronic contribution in principal axis system/ {
+split(el,a); for(i=0;i<3;i++)getline;
+if(e($2-a[1],tol) || e($3-a[2],tol) ||e($4-a[3],tol)) exit 1
+getline;
+if(e($2-a[4],tol) || e($3-a[5],tol) ||e($4-a[6],tol)) exit 1
+getline;
+if(e($2-a[7],tol) || e($3-a[8],tol) ||e($4-a[9],tol)) exit 1
+founde=1
+}
+END{exit( (foundt && foundn && founde) ? 0 : 1) }
+' $log  || ERRLIST="$ERRLIST; G-TENSORS"
 }
