Improve tests, printouts and more. Removed obsolete code. Polish.
    Improved coverage and speed of tests. Also made some changes to
    printouts in Dalton output file. Added license info. Better
    testing for large induced dipoles. Removed obsolete code.

diff --git a/DALTON/test/pehf_nomb b/DALTON/test/pehf_nomb
--- a/DALTON/test/pehf_nomb
+++ b/DALTON/test/pehf_nomb
@@ -17,21 +17,21 @@ fi
 #######################################################################
 #  TEST DESCRIPTION
 #######################################################################
-cat > pehf_small_gspol.info <<'%EOF%'
-   pehf_small_gspol
+cat > pehf_nomb.info <<'%EOF%'
+   pehf_nomb
    -----------
    Molecule:         Acrolein and two classical water molecules
-   Wave Function:    PE-HF / 6-31+G*
-   Test Purpose:     Test of energies, dipole moment and excitation
-                     energies through ABACUS using frozen ground-state
-                     environment polarization
+   Wave Function:    PE-HF / STO-3G
+   Test Purpose:     Testing the many-body neglect approximation option
+                     of the PE library using the iterative and direct
+                     solver for induced moments
 %EOF%
 #######################################################################
 #  MOLECULE INPUT
 #######################################################################
-cat > pehf_small_gspol.mol <<'%EOF%'
+cat > pehf_nomb.mol <<'%EOF%'
 BASIS
-6-31+G*
+STO-3G
 Acrolein
 ------------------------
 AtomTypes=3 NoSymmetry Angstrom
@@ -50,8 +50,8 @@ H              2.675323   -2.516779   -0.000673
 #######################################################################
 #  POTENTIAL INPUT
 #######################################################################
-cat > pehf_small_gspol.pot <<'%EOF%'
-! Two water molecules modelled by a Polarizable Embedding potential
+cat > pehf_nomb.pot <<'%EOF%'
+! Two water molecules with enlarged isotropic polarizability
 coordinates
 10
 AA
@@ -137,34 +137,37 @@ exclists
 #######################################################################
 #  DALTON INPUT
 #######################################################################
-cat > pehf_small_gspol.dal <<'%EOF%'
+cat > pehf_nomb__1.dal <<'%EOF%'
 **DALTON
-.RUN PROPERTIES
-*PEQM
+.RUN WAVE FUNCTION
 .PEQM
+*PEQM
+.VERBOSE
 .ITERATIVE
-1.0d-8
-.GSPOL
+1.0d-10
+.NOMB
 **WAVE FUNCTIONS
 .HF
-*SCF INPUT
-.THRESHOLD
-1.0d-8
-**PROPERTIES
-.EXCITA
-*EXCITA
-.NEXCIT
-4
-.DIPSTR
-.THRESH
-1.0D-4
 **END OF
 %EOF%
+cat > pehf_nomb__2.dal <<'%EOF%'
+**DALTON
+.RUN WAVE FUNCTION
+.PEQM
+*PEQM
+.VERBOSE
+.DIRECT
+.NOMB
+**WAVE FUNCTIONS
+.HF
+**END OF
+%EOF%
+
 #######################################################################
 #  CHECK SCRIPT
 #######################################################################
-echo $CHECK_SHELL > pehf_small_gspol.check
-cat >> pehf_small_gspol.check <<'%EOF%'
+echo $CHECK_SHELL > pehf_nomb__1.check
+cat >> pehf_nomb__1.check <<'%EOF%'
 log=$1
 
 if [ `uname` = Linux ]; then
@@ -174,64 +177,61 @@ else
 fi
 
 #
-# Potential readin test
+# Potential readin
 #
 CRIT1=`$GREP "Number of classical sites: * 10" $log | wc -l`
-CRIT2=`$GREP "Multipole moments upto 3rd order." $log | wc -l`
-CRIT3=`$GREP "Dipole-dipole polarizabilities." $log | wc -l`
-CRIT4=`$GREP "Iterative solver for induced moments" $log | wc -l`
-CRIT5=`$GREP "convergence threshold: 1.0E-08" $log | wc -l`
-CRIT6=`$GREP "Dynamic response from environment will be neglected" $log | wc -l`
+CRIT2=`$GREP "Multipole moments upto 3rd order" $log | wc -l`
+CRIT3=`$GREP "Dipole-dipole polarizabilities" $log | wc -l`
+CRIT4=`$GREP "Many-body interactions will be neglected" $log | wc -l`
+CRIT5=`$GREP "Iterative solver for induced moments will be used" $log | wc -l`
+CRIT6=`$GREP "with convergence threshold: 1\.0E\-10" $log | wc -l`
 TEST[1]=`expr $CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4 \+ $CRIT5 \+ $CRIT6 `
 CTRL[1]=6
 ERROR[1]="INCORRECT POTENTIAL"
+
 #
-# Potential readin test
+# Convergence
 #
-CRIT1=`$GREP "*** DIIS converged in  18 iterations" $log | wc -l`
+CRIT1=`$GREP "*** DIIS converged in  10 iterations" $log | wc -l`
 TEST[2]=`expr $CRIT1 `
 CTRL[2]=1
 ERROR[2]="CONVERGENCE PROBLEM"
+
 #
-# Energy tests
+# Energies
 #
-CRIT1=`$GREP "Monopoles * (\-|\-0)\.028474" $log | wc -l`
-CRIT2=`$GREP "Dipoles * (|0)\.006956" $log | wc -l`
-CRIT3=`$GREP "Quadrupoles * (\-|\-0)\.009139" $log | wc -l`
-CRIT4=`$GREP "Octopoles * (\-|\-0)\.002683" $log | wc -l`
-CRIT5=`$GREP "Electronic * (\-|\-0)\.087358" $log | wc -l`
-CRIT6=`$GREP "Nuclear       * (|0)\.084104" $log | wc -l`
-CRIT7=`$GREP "Multipole * (|0)\.000258" $log | wc -l`
-CRIT8=`$GREP "Total PE energy: * (\-|\-0)\.036337" $log | wc -l`
-CRIT9=`$GREP "Final HF energy: * \-190\.797638" $log | wc -l`
+CRIT1=`$GREP "Monopoles * (\-|\-0)\.015407......" $log | wc -l`
+CRIT2=`$GREP "Dipoles * (|0)\.004184......" $log | wc -l`
+CRIT3=`$GREP "Quadrupoles * (\-|\-0)\.004910......" $log | wc -l`
+CRIT4=`$GREP "Octopoles * (\-|\-0)\.002292......" $log | wc -l`
+CRIT5=`$GREP "Electronic * (\-|\-0)\.044340......" $log | wc -l`
+CRIT6=`$GREP "Nuclear * (|0)\.043425......" $log | wc -l`
+CRIT7=`$GREP "Multipole * (|0)\.000132......" $log | wc -l`
+CRIT8=`$GREP "Total PE energy: * (\-|\-0)\.019208......" $log | wc -l`
+CRIT9=`$GREP "Final HF energy: * \-188\.317408......" $log | wc -l`
 TEST[3]=`expr $CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4 \+ $CRIT5 \+ $CRIT6 \+ $CRIT7 \+ $CRIT8 \+ $CRIT9 `
 CTRL[3]=9
-ERROR[3]="PE-HF ENERGY CONTRIBUTIONS NOT CORRECT"
+ERROR[3]="ENERGY CONTRIBUTIONS NOT CORRECT"
 
 #
-# dipole moment of acrolein
+# Induced dipole moments in environment
 #
-CRIT1=`$GREP "x * 1\.00264" $log | wc -l`
-CRIT2=`$GREP "y * \-1\.81087" $log | wc -l`
-CRIT3=`$GREP "z * (\-|\-0)\.00005" $log | wc -l`
-TEST[4]=`expr $CRIT1 \+ $CRIT2 \+ $CRIT3 `
-CTRL[4]=3
-ERROR[4]="DIPOLE MOMENT NOT CORRECT"
-
-
-#
-# Test of PE-HF excitation energies
-#
-CRIT1=`$GREP "   1        1 * (|0)\.1893" $log | wc -l`
-CRIT2=`$GREP "   1        2 * (|0)\.2421" $log | wc -l`
-CRIT3=`$GREP "   1        3 * (|0)\.3104" $log | wc -l`
-CRIT4=`$GREP "   1        4 * (|0)\.3230" $log | wc -l`
-TEST[5]=`expr $CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4 `
-CTRL[5]=4
-ERROR[5]="PE-HF EXCITATION ENERGIES NOT CORRECT"
+ CRIT1=`$GREP "*  1 * (|0)\.005001.. * (|0)\.010434.. * (|0)\.000004.." $log | wc -l`
+ CRIT2=`$GREP "*  2 * (|0)\.013144.. * (|0)\.007084.. * (|0)\.000007.." $log | wc -l`
+ CRIT3=`$GREP "*  3 * (|0)\.001523.. * (|0)\.000413.. * (|0)\.000000.." $log | wc -l`
+ CRIT4=`$GREP "*  4 * (|0)\.035302.. * (|0)\.024697.. * (|0)\.000026.." $log | wc -l`
+ CRIT5=`$GREP "*  5 * (|0)\.002414.. * (\-|\-0)\.000391.. * (\-|\-0)\.000001.." $log | wc -l`
+ CRIT6=`$GREP "*  6 * (\-|\-0)\.013908.. * (|0)\.004189.. * (|0)\.000003.." $log | wc -l`
+ CRIT7=`$GREP "*  7 * (\-|\-0)\.014953.. * (\-|\-0)\.006800.. * (|0)\.000000.." $log | wc -l`
+ CRIT8=`$GREP "*  8 * (\-|\-0)\.001416.. * (\-|\-0)\.000791.. * (\-|\-0)\.000004.." $log | wc -l`
+ CRIT9=`$GREP "*  9 * (\-|\-0)\.044463.. * (\-|\-0)\.014073.. * (|0)\.000008.." $log | wc -l`
+CRIT10=`$GREP "* 10 * (\-|\-0)\.002380.. * (\-|\-0)\.000434.. * (\-|\-0)\.000009.." $log | wc -l`
+TEST[4]=`expr $CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4 \+ $CRIT5 \+ $CRIT6 \+ $CRIT7 \+ $CRIT8 \+ $CRIT9 \+ $CRIT10 `
+CTRL[4]=10
+ERROR[4]="INDUCED DIPOLE MOMENTS NOT CORRECT"
 
 PASSED=1 
-for i in 1 2 3 4 5
+for i in 1 2 3 4
 do
    if [ ${TEST[i]} -ne ${CTRL[i]} ]; then
      echo "${ERROR[i]} ( test = ${TEST[i]}; control = ${CTRL[i]} ); "
@@ -248,5 +248,85 @@ else
   exit 1
 fi                
 %EOF%
-chmod +x pehf_small_gspol.check
+echo $CHECK_SHELL > pehf_nomb__2.check
+cat >> pehf_nomb__2.check <<'%EOF%'
+log=$1
+
+if [ `uname` = Linux ]; then
+   GREP="egrep -a"
+else
+   GREP="egrep"
+fi
+
+#
+# Potential readin
+#
+CRIT1=`$GREP "Number of classical sites: * 10" $log | wc -l`
+CRIT2=`$GREP "Multipole moments upto 3rd order." $log | wc -l`
+CRIT3=`$GREP "Dipole-dipole polarizabilities." $log | wc -l`
+CRIT4=`$GREP "Many-body interactions will be neglected" $log | wc -l`
+CRIT5=`$GREP "Direct solver for induced moments will be used." $log | wc -l`
+TEST[1]=`expr $CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4 \+ $CRIT5 `
+CTRL[1]=5
+ERROR[1]="INCORRECT POTENTIAL"
+
+#
+# Convergence
+#
+CRIT1=`$GREP "*** DIIS converged in  10 iterations" $log | wc -l`
+TEST[2]=`expr $CRIT1 `
+CTRL[2]=1
+ERROR[2]="CONVERGENCE PROBLEM"
+
+#
+# Energies
+#
+CRIT1=`$GREP "Monopoles * (\-|\-0)\.015407......" $log | wc -l`
+CRIT2=`$GREP "Dipoles * (|0)\.004184......" $log | wc -l`
+CRIT3=`$GREP "Quadrupoles * (\-|\-0)\.004910......" $log | wc -l`
+CRIT4=`$GREP "Octopoles * (\-|\-0)\.002292......" $log | wc -l`
+CRIT5=`$GREP "Electronic * (\-|\-0)\.044340......" $log | wc -l`
+CRIT6=`$GREP "Nuclear * (|0)\.043425......" $log | wc -l`
+CRIT7=`$GREP "Multipole * (|0)\.000132......" $log | wc -l`
+CRIT8=`$GREP "Total PE energy: * (\-|\-0)\.019208......" $log | wc -l`
+CRIT9=`$GREP "Final HF energy: * \-188\.317408......" $log | wc -l`
+TEST[3]=`expr $CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4 \+ $CRIT5 \+ $CRIT6 \+ $CRIT7 \+ $CRIT8 \+ $CRIT9 `
+CTRL[3]=9
+ERROR[3]="ENERGY CONTRIBUTIONS NOT CORRECT"
+
+#
+# Induced dipole moments in environment
+#
+ CRIT1=`$GREP "*  1 * (|0)\.005001.. * (|0)\.010434.. * (|0)\.000004.." $log | wc -l`
+ CRIT2=`$GREP "*  2 * (|0)\.013144.. * (|0)\.007084.. * (|0)\.000007.." $log | wc -l`
+ CRIT3=`$GREP "*  3 * (|0)\.001523.. * (|0)\.000413.. * (|0)\.000000.." $log | wc -l`
+ CRIT4=`$GREP "*  4 * (|0)\.035302.. * (|0)\.024697.. * (|0)\.000026.." $log | wc -l`
+ CRIT5=`$GREP "*  5 * (|0)\.002414.. * (\-|\-0)\.000391.. * (\-|\-0)\.000001.." $log | wc -l`
+ CRIT6=`$GREP "*  6 * (\-|\-0)\.013908.. * (|0)\.004189.. * (|0)\.000003.." $log | wc -l`
+ CRIT7=`$GREP "*  7 * (\-|\-0)\.014953.. * (\-|\-0)\.006800.. * (|0)\.000000.." $log | wc -l`
+ CRIT8=`$GREP "*  8 * (\-|\-0)\.001416.. * (\-|\-0)\.000791.. * (\-|\-0)\.000004.." $log | wc -l`
+ CRIT9=`$GREP "*  9 * (\-|\-0)\.044463.. * (\-|\-0)\.014073.. * (|0)\.000008.." $log | wc -l`
+CRIT10=`$GREP "* 10 * (\-|\-0)\.002380.. * (\-|\-0)\.000434.. * (\-|\-0)\.000009.." $log | wc -l`
+TEST[4]=`expr $CRIT1 \+ $CRIT2 \+ $CRIT3 \+ $CRIT4 \+ $CRIT5 \+ $CRIT6 \+ $CRIT7 \+ $CRIT8 \+ $CRIT9 \+ $CRIT10 `
+CTRL[4]=10
+ERROR[4]="INDUCED DIPOLE MOMENTS NOT CORRECT"
+
+PASSED=1 
+for i in 1 2 3 4
+do
+   if [ ${TEST[i]} -ne ${CTRL[i]} ]; then
+     echo "${ERROR[i]} ( test = ${TEST[i]}; control = ${CTRL[i]} ); "
+     PASSED=0
+   fi
+done
+
+if [ $PASSED -eq 1 ]
+then
+  echo TEST ENDED PROPERLY
+  exit 0
+else
+  echo THERE IS A PROBLEM
+  exit 1
+fi                
+%EOF%
 #######################################################################
