merge DALTON and LSDALTON cmake frameworks
see INSTALL.rst and TESTING.rst for changes

diff --git a/DALTON/test/TEST b/DALTON/test/TEST
--- a/DALTON/test/TEST
+++ b/DALTON/test/TEST
@@ -234,7 +234,6 @@ Usage: $0 [-h|-help|--help] [-keep] [-reftest] [-benchmark]
        -dalton script       : use script instead of the default
                               dalton-script "`pwd`/../dalton" (absolute path) 
        -log logfile         : write output into logfile instead of to "TESTLOG"
-       -cmake               : create cmake/Tests.cmake and exit (except perl tests!)
 
        and where testcase might be one of the following:
           short                -- run all short testcases
@@ -289,7 +288,6 @@ errprint(){
 TESTparams="$0 $*"
 help=""
 keep="false"
-cmake="false"
 paramlist=""
 par_paramlist="-N 4"
 reftest=""
@@ -317,7 +315,6 @@ while echo $1 | egrep -q '^-'; do
      "-dalton" )  shift; DALTON=$1; shift;;
      "-log" ) shift; listing=$1; shift;;
      "-keep" ) keep="true"; shift;;
-     "-cmake" ) cmake="true"; shift;;
      -param* ) shift; paramlist="$1"; shift;;
      "-reftest" ) reftest="true"; shift;;
      "-y") answer_yes=true; shift;;
@@ -339,21 +336,18 @@ if [ "${DALTON:0:1}" != "/" ]; then
   DALTON="$PWD/$DALTON"   # we need absolute path, not relative path
 fi
 
-if [ "$cmake" = "false" ]; then
-    if [ ! -x $DALTON ]; then
-       echo ' '
-       echo '----> ERROR, the "dalton" job script '
-       echo    '"'$DALTON'"'
-       echo '  does not exist or is not executable.'
-       echo 'The person who installed dalton has probably selected'
-       echo '  another place for the "dalton" job script.'
-       echo 'Please modify the DALTON variable in this script (i.e. '$0')'
-       echo '  to point to that place.    Alternatively, you may'
-       echo '  specify where the dalton script is with the -dalton option'
-       echo ' '
-    #  usage
-       exit 1
-    fi
+if [ ! -x $DALTON ]; then
+   echo ' '
+   echo '----> ERROR, the "dalton" job script '
+   echo    '"'$DALTON'"'
+   echo '  does not exist or is not executable.'
+   echo 'The person who installed dalton has probably selected'
+   echo '  another place for the "dalton" job script.'
+   echo 'Please modify the DALTON variable in this script (i.e. '$0')'
+   echo '  to point to that place.    Alternatively, you may'
+   echo '  specify where the dalton script is with the -dalton option'
+   echo ' '
+   exit 1
 fi
 
 #########################################################################
@@ -575,18 +569,6 @@ problems=""
 exitcode=0
 numresult=0
 num_reftests_not_found=0
-
-# create cmake/Tests.cmake
-if [ "$cmake" = "true" ]; then
-   for item in ${testcase}; do
-       echo "add_test($item \${CMAKE_SOURCE_DIR}/test/TEST -dalton \${CMAKE_BINARY_DIR}/dalton -log /dev/null $item)"
-   done
-   cd $SCRIPT_DIR
-   for item in *.tst; do
-       echo "add_test($item \${CMAKE_SOURCE_DIR}/test/TEST -dalton \${CMAKE_BINARY_DIR}/dalton -log /dev/null $item)"
-   done
-   exit 0
-fi
 
 total_tests=0
 for item in ${testcase}
