First save in test_cc directory, which I had forgotten about. Just as I thought almost done ... Several more problems found and fixed using these tests (see my commits from the last couple of days)
* The reference outputs are moved to the new trueresult directory, as in
test/.
* Changed deprecated keywords in tests.
* Updated test criteria
* changed 6-31G* to 6-31G** (erroneously He contained a 2p in old
  6-31G*, and the 2p was used in the test)

diff --git a/test_cc/TEST b/test_cc/TEST
--- a/test_cc/TEST
+++ b/test_cc/TEST
@@ -1,4 +1,4 @@
-#!/bin/ksh 
+#!/bin/bash 
 #########################################################################
 #
 # Shell script for running DALTON test suite
@@ -6,7 +6,20 @@
 # by Christof Haettig and Kasper Hald, Sep. 2000
 #
 #########################################################################
-#
+
+# Note: DALTON points to the default installation directory,
+#       in the 'configure' script. If the person installing
+#       Dalton has chosen another installation directory when
+#       he/she ran 'configure', the you should modify the
+#       DALTON definition to pint to that place.
+
+if [ -x '/usr/bin/time' ]; then
+ TIMING_OF="/usr/bin/time" #hjaaj sep07: gnu time gives more info than built-in time
+else
+ TIMING_OF=" "
+fi
+DALTON="`pwd`/../bin/dalton"
+
 #########################################################################
 # define all the different test suites
 #########################################################################
@@ -38,16 +51,13 @@ usage: TEST [-h|-help|--help] [-keep] [-reftest] [-bell] [-benchmark]
 
        -h | -help | --help  : show this help description
        -keep                : keep *.mol, *.dal, *.check and *.log files
-       -reftest             : test reference file(s); do not run any
-                              calculations
+       -reftest             : test reference file(s); do not run any calculations
        -bell                : sound bell each time a test fails
-       -benchmark           : print CPU time for each testcase as part of
-                              the summary
+       -benchmark           : print CPU time for each testcase as part of the summary
        -param "option list" : pass "option list" to dalton-script
        -dalton script       : use script instead of the default
-                              dalton-script "../dalton"
-       -log logfile         : write output into logfile instead of the
-                              default "TESTLOG"
+                              dalton-script "`pwd`/../dalton" (absolute path) 
+       -log logfile         : write output into logfile instead of the "TESTLOG"
 
        where testcase might be one of the following:
           essential            -- run a minimal set of essential testcases
@@ -63,11 +73,15 @@ exit 1
 }
 
 #########################################################################
-# function mypring(string): print to stdout and $listing
+# function myprint(string): print to stdout and $listing
 #########################################################################
 myprint(){
  echo "$1";
  echo "$1" >> $listing;
+}
+
+errprint(){
+ echo "$1" >> /dev/stderr;
 }
 
 #########################################################################
@@ -79,9 +93,9 @@ myprint(){
 #########################################################################
 # set defaults and evaluate parameters
 #########################################################################
+TESTparams="$0 $*"
 help=""
 keep="false"
-DALTON="../bin/dalton"
 paramlist=""
 reftest=""
 bell=""
@@ -101,15 +115,30 @@ while [ -n "`echo $1 | grep '-'`" ]; do
      "-dalton" )  shift; DALTON=$1; shift;;
      "-log" ) shift; listing=$1; shift;;
      "-keep" ) keep="true"; shift;;
-     "-param" ) shift; paramlist="$1"; shift;;
+     -param* ) shift; paramlist="$1"; shift;;
      "-reftest" ) reftest="true"; shift;;
      "-bell" ) bell="true"; shift;;
      "-benchmark" ) benchmark="true"; shift;;
-     * ) usage;;
+     * ) echo "---> ERROR: $1 is an unknown option!"; usage;;
    esac
 done
 if [ $help ]; then
   usage
+fi
+
+if [ ! -x $DALTON ]; then
+   echo ' '
+   echo '----> ERROR, the "dalton" job script '
+   echo    '"'$DALTON'"'
+   echo '  does not exist or is not executable.'
+   echo 'The person who installed dalton has probably selected'
+   echo '  another place for the "dalton" job script.'
+   echo 'Please modify the DALTON variable in this script (i.e. '$0')'
+   echo '  to point to that place.    Alternatively, you may'
+   echo '  specify where the dalton script is with the -dalton option'
+   echo ' '
+#  usage
+   exit 1
 fi
 
 #########################################################################
@@ -130,10 +159,21 @@ elif [ "$testcase" = "all" ]; then
   testcase=$ALL
 fi
 
+#########################################################################
+# create a unique directory for test output /hjaaj
+# nonportable characters in the directory name removed. /pawsa
+#########################################################################
+testdir="`date +'%Y-%m-%dT%H_%M'`-testjob-pid-$$"
+while [ -e $testdir ]; do
+    testdir=${testdir}x
+done
+mkdir $testdir 
+cp functions $testdir
+cd $testdir || exit 1
 
 
 #########################################################################
-# check file for test listing:
+# check files for test listing:
 #########################################################################
 if [  -s $listing ]; then
    echo "$listing already exists... should it be deleted first? (y/n)"
@@ -146,8 +186,11 @@ fi
 myprint "#####################################################################"
 myprint "                          DALTON test suite"
 myprint "#####################################################################"
-myprint "dalton script         : $DALTON"
+myprint "invoked with          : $TESTparams"
+myprint "date and time         : `date`"
+myprint "dalton script         : $TIMING_OF $DALTON"
 myprint "parameter list passed : $paramlist"
+myprint "test job directory    : $testdir"
 myprint "test listing          : $listing"
 myprint "test cases            : $testcase"
 
@@ -157,16 +200,24 @@ myprint "test cases            : $testcase"
 passedall="ALL TESTS ENDED PROPERLY!"
 problems=""
 numresult=0
+num_reftests_not_found=0
 for item in ${testcase}
 do
   trouble=0
   myprint "###########################################################"
-  myprint "start now with test $item:"
+  myprint "`date`"
+  myprint "Starting now with test $item:"
   myprint "-----------------------------------------------------------"
-  chmod +x ./$item
-  ./$item
-  if [ -f $item.info ]; then
-    cat $item.info | tee -a $listing
+  errprint "###########################################################"
+  errprint "`date` -- Starting now with test $item:"
+  errprint "-----------------------------------------------------------"
+  chmod +x ../$item || exit 1
+  ../$item
+# remove any directory path now the files are unpacked
+  item=`basename $item`
+  if [ -f $item.info -a "$keep_quiet" = "" ]; then
+    cat $item.info
+    cat $item.info >> $listing
   fi
 # Check if this is a multistep job
   numsteps=1
@@ -202,7 +253,7 @@ do
           dalfile=$item
           logfile=./$item.log
           checkfile=./$item.check
-          reffile=./$item.ref
+          reffile=../trueresult/$item.*ref
       fi
 # If it's a reftest, no calculation is performed
       if [ "$reftest" = "true" ]; then
@@ -262,19 +313,23 @@ do
       fi
       echo $checkout
       passed=`echo $checkout | grep "TEST ENDED PROPERLY"`
-      if [ -n "$passed" ]; then
-        if [ "$keep" = "false" ]; then
-          rm -f $dalfile.dal $checkfile $logfile $item.info
-        fi
-      else
+      if [ -z "$passed" ]; then
         trouble=`expr $trouble \+ 1`
         if [ "$bell" = "true" ]; then
           echo "\a"
         fi
-        passedall="THERE IS A PROBLEM IN TEST CASE"
+        passedall="THERE IS A PROBLEM IN TEST CASE(S)"
         if [ "$trouble" -eq 1 ]; then
             problems="$problems $item"
         fi
+      elif [ "$keep" = "false" ]; then
+        #rm -f $dalfile.dal $dalfile.BAS $checkfile $logfile $item.info
+        rm -f $dalfile.dal $dalfile.BAS $checkfile $item.info # keep $logfile, can be interesting to look closer at
+        if [ "$step" -eq "$numsteps" ]; then
+#       only delete restart files in last step of multistep test !!!
+           rm -f $dalfile.tar.gz
+        fi
+#     else everything OK and -keep defined
       fi
     step=`expr $step \+ 1`
   done
@@ -289,6 +344,7 @@ done
 # final result:
 #########################################################################
 
+myprint ""
 myprint "#####################################################################"
 myprint "                              Summary"
 myprint "#####################################################################"
@@ -302,7 +358,7 @@ if [ "$benchmark" = "true" ]; then
           namelength=`expr length ${testlist[$ind]}`
           spclength=`expr 32 \- $namelength`
           spc=`expr substr "$emptystring" 1 $spclength`
-          myprint "\t${testlist[$ind]}$spc${timelist[$ind]}"
+          myprint "	${testlist[$ind]}$spc${timelist[$ind]}"
           ind=`expr $ind \+ 1`
         done
         echo
@@ -310,6 +366,6 @@ if [ "$benchmark" = "true" ]; then
 fi
 
 echo $passedall | tee -a $listing
-echo $problems | tee -a $listing
+echo $problems  | tee -a $listing
 
 exit 0
